### ISSUE TITLE
Feature: /help command

### ISSUE THREAD

**Issue by LunexSan** [JacksonVirgo/mafia-engine-bot#11]
Add a /help command with multiple options to choose from guiding to wiki articles:

- [ ] All Roles (/help Roles)
- [ ] How to play (/help Howtoplay)
- [ ] GIM main page (/help GIM)
- [ ] wiki main page (/help wiki)
- [ ] list of staff (/help staff)
- [ ] terminology (/help terms)
- [ ] voting terminology (/help votingterms)

**Comment by JacksonVirgo** [comment]
Created and released with the new production version

**Comment by LunexSan** [comment]
For the list of staff wiki link see #19
