### ISSUE TITLE
Idea, New Feature: /commands

### ISSUE THREAD

**Issue by LunexSan** [JacksonVirgo/mafia-engine-bot#20]
a /commands command to list all available bot commands (the public ones), alternatively /staffcommands to list the other ones not available to normal members?

Not quite sure if a split is necessary.
A general command for users to see what all exists **and what it does** might be nice.
Alternatively, instead of hardcoding an embed, as an example, this could be a "type in your command" type of thing, and if an existing command is typed in, an explanation for that command will be output.

I am uncertain as to how necessary this really is, just putting it here as an idea.

**Comment by JacksonVirgo** [comment]
I don't feel this is super necessary due to Discord having a way to see all of the commands, and their descriptions.
If you feel the descriptions I have given to each command are not adequate, I'd recommend opening up a new issue or sending a pull-request with changes.
